# -*- coding: utf-8 -*-
"""Multi_Capability_AI_Assistant(Assignment_1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h58GYk5zvkann7WqbBca0CxAHZLeICym

# Multi-Capability AI Assistant
### Agentic AI Bootcamp — atomcamp | Session 2 Project

**Capabilities:**
1. 📧 Enhanced Email Writer (with web search)
2. 📝 Smart Summarizer (with analytics)
3. 💬 Chat Assistant (with memory)

**Tools:**
1. 🔢 Calculator
2. 🔍 Web Search (mock)
3. 📊 Data Analyzer
4. 🌤️ Weather Tool (mock)

> **Note:** Uses **Groq API** (free) — make sure your `GROQ_API_KEY` is set in Colab Secrets.

---
## Installing Dependencies
"""

# Install required packages
!pip install groq --quiet
print("✅ Dependencies installed!")

"""---
## Loading API Key from Colab Secrets
"""

import os

# Load from Colab Secrets (Key name: 'groq')
try:
    from google.colab import userdata
    GROQ_API_KEY = userdata.get('groq')
    if GROQ_API_KEY:
        print("✅ Groq API key loaded from Colab Secrets!")
    else:
        raise ValueError("Key is empty")
except Exception as e:
    # Fallback: set manually
    GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "")
    if GROQ_API_KEY:
        print("✅ Groq API key loaded from environment!")
    else:
        print("⚠️  API key not found. Please add 'groq' to Colab Secrets (🔑 icon on left sidebar).")

os.environ["GROQ_API_KEY"] = GROQ_API_KEY

"""---
## Defining All Tool Functions
"""

import json
import math
import statistics

# ─────────────────────────────────────────────
# TOOL 1: Calculator
# ─────────────────────────────────────────────
def calculate(expression: str) -> str:
    """
    Safely evaluates a mathematical expression.
    Supports: +, -, *, /, **, sqrt, log, sin, cos, tan, pi, e
    """
    try:
        # Safe math context — only allow math functions
        allowed = {
            "__builtins__": {},
            "sqrt": math.sqrt,
            "log": math.log,
            "sin": math.sin,
            "cos": math.cos,
            "tan": math.tan,
            "pi": math.pi,
            "e": math.e,
            "abs": abs,
            "round": round,
        }
        result = eval(expression, allowed)
        return json.dumps({
            "expression": expression,
            "result": round(result, 6),
            "status": "success"
        })
    except ZeroDivisionError:
        return json.dumps({"error": "Division by zero is not allowed.", "status": "error"})
    except Exception as e:
        return json.dumps({"error": f"Could not evaluate: {str(e)}", "status": "error"})


# ─────────────────────────────────────────────
# TOOL 2: Web Search (Mock)
# ─────────────────────────────────────────────
def web_search(query: str) -> str:
    """
    Mock web search tool. Returns realistic-looking search results
    for common topics. Replace with a real API (e.g. SerpAPI) for production.
    """
    query_lower = query.lower()

    mock_results = {
        "python": [
            {"title": "Python Official Documentation", "snippet": "Python is a high-level, general-purpose programming language emphasizing code readability.", "url": "https://python.org"},
            {"title": "Python Tutorial - W3Schools", "snippet": "Python is easy to learn and has a simple, clean syntax. It supports OOP, functional, and procedural styles.", "url": "https://w3schools.com/python"}
        ],
        "ai": [
            {"title": "Artificial Intelligence - Overview", "snippet": "AI enables machines to perform tasks that normally require human intelligence, such as reasoning, learning, and problem-solving.", "url": "https://en.wikipedia.org/wiki/Artificial_intelligence"},
            {"title": "Latest AI Trends 2025", "snippet": "In 2025, AI breakthroughs include multimodal models, agentic systems, and widespread enterprise adoption.", "url": "https://techcrunch.com/ai-trends"}
        ],
        "climate": [
            {"title": "Climate Change - NASA", "snippet": "Global temperatures have risen by about 1.1°C since the pre-industrial era. Urgent action is needed to limit warming to 1.5°C.", "url": "https://climate.nasa.gov"},
            {"title": "IPCC Report Summary", "snippet": "The IPCC warns that without drastic emissions cuts, extreme weather events will become far more frequent by 2050.", "url": "https://ipcc.ch"}
        ],
        "pakistan": [
            {"title": "Pakistan - Overview", "snippet": "Pakistan is a South Asian country with a population of over 230 million. Islamabad is the capital and Karachi the largest city.", "url": "https://en.wikipedia.org/wiki/Pakistan"},
            {"title": "Pakistan Economy 2025", "snippet": "Pakistan's economy shows signs of stabilization in 2025 with improving inflation figures and increased foreign investment.", "url": "https://dawn.com/economy"}
        ],
        "email": [
            {"title": "How to Write a Professional Email", "snippet": "A professional email should have a clear subject line, greeting, body with context, call to action, and polite closing.", "url": "https://grammarly.com/email-tips"},
            {"title": "Email Etiquette Tips", "snippet": "Always proofread before sending. Keep emails concise. Use a descriptive subject line. Reply within 24 hours.", "url": "https://hubspot.com/email-etiquette"}
        ]
    }

    # Match query to known topics
    results = []
    for keyword, data in mock_results.items():
        if keyword in query_lower:
            results = data
            break

    if not results:
        results = [
            {"title": f"Search Results for '{query}'", "snippet": f"Found relevant information about '{query}'. This topic involves multiple perspectives and recent developments in 2024-2025.", "url": f"https://search.example.com?q={query.replace(' ', '+')}"},
            {"title": f"{query.title()} - Wikipedia", "snippet": f"{query.title()} is a widely discussed topic. Recent studies and expert analysis provide key insights on this subject.", "url": f"https://en.wikipedia.org/wiki/{query.replace(' ', '_')}"}
        ]

    return json.dumps({
        "query": query,
        "results_count": len(results),
        "results": results,
        "status": "success"
    })


# ─────────────────────────────────────────────
# TOOL 3: Data Analyzer
# ─────────────────────────────────────────────
def analyze_data(data: list, operation: str = "all") -> str:
    """
    Analyzes a list of numbers.
    Operations: sum, average, max, min, median, std, all
    """
    try:
        # Validate input
        if not data:
            return json.dumps({"error": "Data list is empty.", "status": "error"})

        # Convert all to float
        nums = [float(x) for x in data]
        op = operation.lower().strip()

        ops_map = {
            "sum":     lambda n: sum(n),
            "average": lambda n: statistics.mean(n),
            "mean":    lambda n: statistics.mean(n),
            "max":     lambda n: max(n),
            "min":     lambda n: min(n),
            "median":  lambda n: statistics.median(n),
            "std":     lambda n: statistics.stdev(n) if len(n) > 1 else 0,
            "count":   lambda n: len(n),
        }

        if op == "all":
            result = {
                "count":   len(nums),
                "sum":     round(sum(nums), 4),
                "average": round(statistics.mean(nums), 4),
                "median":  round(statistics.median(nums), 4),
                "max":     max(nums),
                "min":     min(nums),
                "std_dev": round(statistics.stdev(nums), 4) if len(nums) > 1 else 0,
            }
        elif op in ops_map:
            result = {operation: round(ops_map[op](nums), 4)}
        else:
            return json.dumps({"error": f"Unknown operation '{operation}'. Use: sum, average, max, min, median, std, all", "status": "error"})

        return json.dumps({"data": nums, "result": result, "status": "success"})

    except (ValueError, TypeError) as e:
        return json.dumps({"error": f"Invalid data: {str(e)}", "status": "error"})


# ─────────────────────────────────────────────
# TOOL 4: Weather Tool (Mock)
# ─────────────────────────────────────────────
def get_weather(location: str) -> str:
    """
    Mock weather tool for common Pakistani and global cities.
    Replace with OpenWeatherMap API for real data.
    """
    weather_db = {
        # Pakistan
        "karachi":        {"temp_c": 32, "condition": "Partly Cloudy",  "humidity": 72, "wind_kmh": 18},
        "lahore":         {"temp_c": 38, "condition": "Sunny",          "humidity": 45, "wind_kmh": 12},
        "islamabad":      {"temp_c": 33, "condition": "Clear",          "humidity": 40, "wind_kmh": 10},
        "multan":         {"temp_c": 42, "condition": "Hot & Sunny",    "humidity": 30, "wind_kmh": 8},
        "peshawar":       {"temp_c": 36, "condition": "Clear",          "humidity": 35, "wind_kmh": 14},
        "quetta":         {"temp_c": 28, "condition": "Cool & Breezy",  "humidity": 38, "wind_kmh": 22},
        "dera ismail khan":{"temp_c": 40, "condition": "Hot & Sunny",   "humidity": 28, "wind_kmh": 9},
        # Global
        "london":         {"temp_c": 15, "condition": "Cloudy",         "humidity": 78, "wind_kmh": 20},
        "new york":       {"temp_c": 22, "condition": "Partly Cloudy",  "humidity": 60, "wind_kmh": 15},
        "dubai":          {"temp_c": 38, "condition": "Sunny",          "humidity": 55, "wind_kmh": 16},
        "tokyo":          {"temp_c": 26, "condition": "Sunny",          "humidity": 65, "wind_kmh": 12},
        "paris":          {"temp_c": 18, "condition": "Overcast",       "humidity": 70, "wind_kmh": 18},
    }

    loc_key = location.lower().strip()
    data = weather_db.get(loc_key)

    if data:
        temp_f = round(data["temp_c"] * 9/5 + 32, 1)
        return json.dumps({
            "location": location.title(),
            "temperature_c": data["temp_c"],
            "temperature_f": temp_f,
            "condition": data["condition"],
            "humidity_percent": data["humidity"],
            "wind_kmh": data["wind_kmh"],
            "status": "success"
        })
    else:
        return json.dumps({
            "location": location,
            "message": f"Weather data not available for '{location}'. Try: Karachi, Lahore, Islamabad, Multan, London, Dubai, New York.",
            "status": "not_found"
        })


print("✅ All 4 tool functions defined!")
print("   🔢 Calculator | 🔍 Web Search | 📊 Data Analyzer | 🌤️ Weather")

"""---
## Defining Tool Schemas (for Groq Function Calling)
"""

# Tool schemas tell the LLM what tools are available and how to call them

TOOL_SCHEMAS = [
    {
        "type": "function",
        "function": {
            "name": "calculate",
            "description": "Evaluate a mathematical expression. Use for any arithmetic, percentages, or math calculations. Supports: +, -, *, /, **, sqrt(), log(), sin(), cos(), pi, e.",
            "parameters": {
                "type": "object",
                "properties": {
                    "expression": {
                        "type": "string",
                        "description": "A valid Python math expression, e.g. '15 * 0.18' or 'sqrt(144)' or '(100 + 200) / 3'"
                    }
                },
                "required": ["expression"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "web_search",
            "description": "Search the web for information on a topic. Use when you need current facts, background research, or up-to-date information before writing content.",
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "The search query string, e.g. 'best practices for professional emails' or 'climate change 2025'"
                    }
                },
                "required": ["query"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "analyze_data",
            "description": "Analyze a list of numbers. Calculates sum, average, max, min, median, and standard deviation.",
            "parameters": {
                "type": "object",
                "properties": {
                    "data": {
                        "type": "array",
                        "items": {"type": "number"},
                        "description": "List of numbers to analyze, e.g. [10, 20, 30, 40, 50]"
                    },
                    "operation": {
                        "type": "string",
                        "description": "Operation to perform: 'sum', 'average', 'max', 'min', 'median', 'std', or 'all'. Default: 'all'",
                        "enum": ["sum", "average", "max", "min", "median", "std", "all"]
                    }
                },
                "required": ["data"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "get_weather",
            "description": "Get the current weather for a city. Supports Pakistani cities (Karachi, Lahore, Islamabad, Multan, Peshawar, Quetta, Dera Ismail Khan) and major global cities.",
            "parameters": {
                "type": "object",
                "properties": {
                    "location": {
                        "type": "string",
                        "description": "Name of the city, e.g. 'Karachi' or 'London'"
                    }
                },
                "required": ["location"]
            }
        }
    }
]

# Map tool names to actual Python functions
TOOL_FUNCTIONS = {
    "calculate":    calculate,
    "web_search":   web_search,
    "analyze_data": analyze_data,
    "get_weather":  get_weather,
}

print("✅ Tool schemas defined!")
print(f"   Total tools registered: {len(TOOL_SCHEMAS)}")

"""---
## Building the Multi-Capability Assistant Class
"""

from groq import Groq
import textwrap

class MultiCapabilityAssistant:
    """
    A Multi-Capability AI Assistant powered by Groq (llama-3.3-70b-versatile).

    Capabilities:
      1. Enhanced Email Writer  — research + draft emails in any tone
      2. Smart Summarizer       — summarize text with analytics
      3. Chat Assistant         — conversational chat with memory

    Tools: Calculator, Web Search, Data Analyzer, Weather
    """

    MODEL = "llama-3.3-70b-versatile"  # Free Groq model
    MAX_TOKENS = 1024

    def __init__(self, api_key: str):
        """Initialize the assistant with a Groq API key."""
        if not api_key:
            raise ValueError("❌ GROQ_API_KEY is missing! Add it to Colab Secrets.")

        self.client = Groq(api_key=api_key)
        self.chat_history = []  # Persistent memory for Chat capability
        self.tools = TOOL_SCHEMAS
        self.functions = TOOL_FUNCTIONS
        print("✅ MultiCapabilityAssistant initialized!")
        print(f"   Model: {self.MODEL}")

    # ─────────────────────────────────────────────
    # CORE: Tool Execution Engine
    # ─────────────────────────────────────────────
    def _execute_tool(self, tool_name: str, tool_args: dict) -> str:
        """Execute a tool by name and return its result as a string."""
        if tool_name not in self.functions:
            return json.dumps({"error": f"Unknown tool: {tool_name}"})
        try:
            return self.functions[tool_name](**tool_args)
        except Exception as e:
            return json.dumps({"error": f"Tool '{tool_name}' failed: {str(e)}"})

    def _call_llm(self, messages: list, use_tools: bool = True) -> any:
        """Call the Groq LLM with optional tool use. Returns the response object."""
        kwargs = {
            "model": self.MODEL,
            "messages": messages,
            "max_tokens": self.MAX_TOKENS,
            "temperature": 0.7,
        }
        if use_tools:
            kwargs["tools"] = self.tools
            kwargs["tool_choice"] = "auto"

        return self.client.chat.completions.create(**kwargs)

    def _run_agent_loop(self, messages: list) -> str:
        """
        Agentic loop: keeps calling tools until the model produces
        a final text response with no more tool calls.
        """
        while True:
            response = self._call_llm(messages)
            msg = response.choices[0].message

            # If no tool calls, we have the final answer
            if not msg.tool_calls:
                return msg.content or "(No response generated)"

            # Process each tool call
            messages.append(msg)  # Add assistant's tool-call message

            for tc in msg.tool_calls:
                tool_name = tc.function.name
                tool_args = json.loads(tc.function.arguments)

                print(f"   🔧 Using tool: {tool_name}({', '.join(f'{k}={v!r}' for k,v in tool_args.items())})")

                tool_result = self._execute_tool(tool_name, tool_args)

                # Add tool result to messages
                messages.append({
                    "role": "tool",
                    "tool_call_id": tc.id,
                    "content": tool_result,
                })

    # ─────────────────────────────────────────────
    # CAPABILITY 1: Enhanced Email Writer
    # ─────────────────────────────────────────────
    def write_email(
        self,
        description: str,
        tone: str = "formal",
        research: bool = False
    ) -> str:
        """
        Write a complete email based on a description.

        Args:
            description: What the email is about
            tone: 'formal', 'friendly', or 'casual'
            research: If True, searches the web before writing
        """
        # Input validation
        if not description.strip():
            return "❌ Please provide a description of the email you need."

        tone = tone.lower().strip()
        if tone not in ["formal", "friendly", "casual"]:
            print(f"   ⚠️  Unknown tone '{tone}', defaulting to 'formal'.")
            tone = "formal"

        system_prompt = f"""You are an expert email writer. Your task is to write a complete,
professional email based on the user's description.

Tone: {tone.upper()}
- formal: Professional, respectful, structured. Use proper salutations and closings.
- friendly: Warm and approachable but still professional.
- casual: Relaxed, conversational. OK to use contractions and informal language.

ALWAYS output in this exact format:
Subject: [subject line here]

[full email body]"""

        research_note = "Use the web_search tool to research relevant facts before writing if needed." if research else ""

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user",   "content": f"Write a {tone} email about: {description}\n{research_note}"}
        ]

        print(f"\n📧 Email Writer | Tone: {tone} | Research: {'Yes' if research else 'No'}")
        print("   Processing...")

        try:
            result = self._run_agent_loop(messages)
            return result
        except Exception as e:
            return f"❌ Email generation failed: {str(e)}"

    # ─────────────────────────────────────────────
    # CAPABILITY 2: Smart Summarizer
    # ─────────────────────────────────────────────
    def summarize(
        self,
        text: str,
        length: str = "medium"
    ) -> str:
        """
        Summarize text and show analytics.

        Args:
            text: The text to summarize
            length: 'short' (1 sentence), 'medium' (2-3 sentences), 'long' (4-5 sentences)
        """
        # Input validation
        if not text.strip():
            return "❌ Please provide text to summarize."
        if len(text.split()) < 10:
            return "❌ Text is too short to summarize (minimum 10 words)."

        length = length.lower().strip()
        length_map = {
            "short":  "1 concise sentence",
            "medium": "2-3 sentences",
            "long":   "4-5 sentences covering main points"
        }
        if length not in length_map:
            length = "medium"
        length_instruction = length_map[length]

        # Calculate analytics BEFORE summarizing
        original_words = len(text.split())
        original_chars = len(text)
        original_sentences = text.count('.') + text.count('!') + text.count('?')

        print(f"\n📝 Summarizer | Length: {length} | Input: {original_words} words")
        print("   Processing...")

        messages = [
            {
                "role": "system",
                "content": f"You are a precise text summarizer. Summarize the given text in exactly {length_instruction}. Be accurate and capture the main idea. Return ONLY the summary, nothing else."
            },
            {"role": "user", "content": f"Summarize this text:\n\n{text}"}
        ]

        try:
            # Summarizer doesn't need tools — call directly
            response = self._call_llm(messages, use_tools=False)
            summary = response.choices[0].message.content.strip()

            # Post-summary analytics
            summary_words = len(summary.split())
            summary_chars = len(summary)
            reduction_pct = round((1 - summary_words / original_words) * 100, 1) if original_words else 0

            # Format output
            output = f"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📊 SUMMARY ANALYTICS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Original : {original_words:>5} words | {original_chars:>6} characters | ~{original_sentences} sentences
  Summary  : {summary_words:>5} words | {summary_chars:>6} characters
  Reduced  : {reduction_pct}% shorter
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📝 SUMMARY ({length.upper()})
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{summary}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"""
            return output

        except Exception as e:
            return f"❌ Summarization failed: {str(e)}"

    # ─────────────────────────────────────────────
    # CAPABILITY 3: Chat Assistant (with Memory)
    # ─────────────────────────────────────────────
    def chat(self, user_message: str) -> str:
        """
        Chat with the assistant. Maintains conversation history.
        The assistant can use all 4 tools during chat.

        Args:
            user_message: The user's message
        """
        if not user_message.strip():
            return "❌ Please type a message!"

        SYSTEM_PROMPT = """You are a helpful, knowledgeable AI assistant. You have access to tools:
- calculate: for any math
- web_search: to look up information
- analyze_data: to process lists of numbers
- get_weather: to check weather in cities

Use tools when they'd genuinely help. Be concise, friendly, and accurate.
If asked about previous messages, refer to the conversation history."""

        # Add user message to history
        self.chat_history.append({"role": "user", "content": user_message})

        # Build full message list with system prompt
        messages = [
            {"role": "system", "content": SYSTEM_PROMPT}
        ] + self.chat_history

        try:
            response_text = self._run_agent_loop(messages)

            # Save assistant response to history
            self.chat_history.append({"role": "assistant", "content": response_text})

            return response_text

        except Exception as e:
            error_msg = f"❌ Chat error: {str(e)}"
            self.chat_history.append({"role": "assistant", "content": error_msg})
            return error_msg

    def clear_chat_history(self):
        """Clear conversation memory."""
        self.chat_history = []
        print("🗑️  Chat history cleared.")

    def show_chat_history(self):
        """Display the conversation history."""
        if not self.chat_history:
            print("📭 No chat history yet.")
            return
        print(f"\n💬 Chat History ({len(self.chat_history)} messages)")
        print("═" * 50)
        for i, msg in enumerate(self.chat_history, 1):
            role = "🧑 You" if msg["role"] == "user" else "🤖 Assistant"
            content = msg["content"][:200] + "..." if len(msg["content"]) > 200 else msg["content"]
            print(f"[{i}] {role}: {content}")
        print("═" * 50)

    # ─────────────────────────────────────────────
    # SMART ROUTER: Detect capability from input
    # ─────────────────────────────────────────────
    def process(self, user_input: str) -> str:
        """
        Auto-routes user input to the right capability.
        - Detects 'email', 'summarize', etc. and routes automatically.
        - Falls back to chat for everything else.
        """
        if not user_input.strip():
            return "❌ Please enter something!"

        text = user_input.lower()

        # Route to Email Writer
        if any(kw in text for kw in ["write email", "draft email", "compose email", "send email"]):
            tone = "formal"
            if "friendly" in text: tone = "friendly"
            if "casual" in text:   tone = "casual"
            research = "research" in text or "search" in text
            return self.write_email(user_input, tone=tone, research=research)

        # Route to Summarizer
        if any(kw in text for kw in ["summarize", "summarise", "summary of", "tldr", "tl;dr"]):
            # Try to extract the text after the keyword
            for kw in ["summarize:", "summarise:", "summary of:", "summarize ", "summarise "]:
                if kw in text:
                    content = user_input[user_input.lower().index(kw) + len(kw):].strip()
                    if content:
                        length = "short" if "short" in text else "long" if "long" in text else "medium"
                        return self.summarize(content, length=length)
            return "❌ Please provide text after 'summarize:'"

        # Everything else → Chat
        return self.chat(user_input)


print("✅ MultiCapabilityAssistant class defined!")

"""## Initializing the Assistant"""

# Create assistant instance
assistant = MultiCapabilityAssistant(api_key=GROQ_API_KEY)

print("""
╔══════════════════════════════════════════════════╗
║      🤖 Multi-Capability AI Assistant           ║
║         Powered by Groq (Free API)              ║
╠══════════════════════════════════════════════════╣
║  Capabilities:                                  ║
║    📧  Enhanced Email Writer                    ║
║    📝  Smart Summarizer                         ║
║    💬  Chat Assistant (with memory)             ║
║                                                  ║
║  Tools: Calculator | Search | Data | Weather    ║
╚══════════════════════════════════════════════════╝
""")

"""---
## Step 7: Demo — Test All Capabilities & Tools

Run each cell below to test each feature.

### Demo 1: Email Writer (Formal)
"""

result = assistant.write_email(
    description="Requesting a week off for a family emergency",
    tone="formal"
)
print(result)

"""### Demo 2: Email Writer (Friendly + Web Research)"""

result = assistant.write_email(
    description="Introducing our new AI product to potential clients",
    tone="friendly",
    research=True   # Will use web_search tool first
)
print(result)

"""### Demo 3: Smart Summarizer (Medium Length)"""

long_text = """
Artificial intelligence (AI) has transformed nearly every industry over the past decade.
From healthcare, where AI assists in diagnosing diseases with accuracy rivaling that of
experienced doctors, to finance, where algorithms detect fraud in milliseconds — the
impact is undeniable. In education, personalized learning platforms adapt to each
student's pace and learning style. Manufacturing has seen AI-driven automation reduce
production errors to near zero. Perhaps most significantly, AI is revolutionizing
scientific research: in 2023, AlphaFold predicted the 3D structure of virtually every
known protein, a breakthrough that had eluded biologists for 50 years. Critics raise
valid concerns about job displacement, algorithmic bias, and the concentration of AI
power in the hands of a few tech giants. Governments worldwide are now racing to
establish regulatory frameworks. Despite challenges, most experts agree that AI will
be one of the most transformative technologies in human history, comparable to the
invention of electricity or the internet.
"""

result = assistant.summarize(long_text, length="medium")
print(result)

"""### Demo 4: Chat with Memory"""

# First message
response = assistant.chat("Hi! My name is Ahmed and I'm learning Python.")
print("🤖", response)

# Follow-up — tests memory
response = assistant.chat("What was my name again, and what am I learning?")
print("🤖", response)

# Tool use in chat
response = assistant.chat("What is 15% of 8500? I need this for calculating tax.")
print("🤖", response)

"""### Demo 5: Calculator Tool"""

response = assistant.chat("Calculate the compound interest on PKR 100,000 at 12% annual rate for 3 years. Formula: P * (1 + r)^t")
print("🤖", response)

"""### Demo 6: Data Analyzer Tool"""

response = assistant.chat("Analyze these monthly sales figures: 45000, 52000, 48000, 61000, 57000, 63000, 70000, 68000, 72000, 75000, 80000, 85000")
print("🤖", response)

"""### Demo 7: Weather Tool"""

response = assistant.chat("What's the weather like in Karachi and Islamabad today?")
print("🤖", response)

"""### Auto-Router (process method)"""

# process() auto-detects what to do
inputs = [
    "Write email to apologize for missing a meeting",
    "Summarize: Python is a high-level programming language known for its readability and simplicity. It was created by Guido van Rossum and released in 1991. Python supports multiple programming paradigms including procedural, object-oriented, and functional programming. It has a large standard library and an active community that has developed thousands of third-party packages.",
    "What is the capital of Pakistan?"
]

for i, inp in enumerate(inputs, 1):
    print(f"\n{'='*60}")
    print(f"INPUT {i}: {inp[:80]}{'...' if len(inp)>80 else ''}")
    print('='*60)
    result = assistant.process(inp)
    print(result)

"""---
## View Chat History
"""

assistant.show_chat_history()

"""---
## Interactive Chat Loop

Run this cell to start an interactive conversation. Type `exit` or `quit` to stop, `history` to see conversation history, `clear` to reset memory.
"""

# Reset for a clean interactive session
assistant.clear_chat_history()

print("""
╔══════════════════════════════════════════════╗
║   🤖 Interactive Assistant — Type Away!     ║
╠══════════════════════════════════════════════╣
║  Commands:                                  ║
║    exit / quit  → Stop the chat             ║
║    history      → Show conversation history ║
║    clear        → Reset memory              ║
║    help         → Show usage examples       ║
╚══════════════════════════════════════════════╝
""")

HELP_TEXT = """
📖 USAGE EXAMPLES:

📧 Email Writer:
   "Write a formal email to request a salary raise"
   "Draft a friendly email inviting team to a party"
   "Compose a casual email asking for deadline extension"

📝 Summarizer:
   "Summarize: [paste your text here]"
   "Short summarize: [text]"
   "Long summarize: [text]"

💬 Chat + Tools:
   "What is sqrt(144) + 20%  of 500?"
   "Analyze data: 10, 25, 30, 45, 50, 65"
   "Weather in Dubai?"
   "Search for info about machine learning"
"""

while True:
    try:
        user_input = input("\n🧑 You: ").strip()
    except (EOFError, KeyboardInterrupt):
        print("\n👋 Goodbye!")
        break

    if not user_input:
        print("   ⚠️  Please type something!")
        continue

    cmd = user_input.lower()

    if cmd in ["exit", "quit", "bye"]:
        print("👋 Goodbye! Hope I was helpful.")
        break
    elif cmd == "history":
        assistant.show_chat_history()
        continue
    elif cmd == "clear":
        assistant.clear_chat_history()
        continue
    elif cmd == "help":
        print(HELP_TEXT)
        continue

    # Process the input
    print("🤖 Assistant: ", end="", flush=True)
    response = assistant.process(user_input)
    print(response)

"""---
## Test Tools Directly (Unit Tests)
"""

import json

print("🧪 Running Tool Unit Tests\n" + "="*50)

# Test 1: Calculator
tests = [
    ("calculate",    {"expression": "15 * 0.18"},                       "15% of 100"),
    ("calculate",    {"expression": "sqrt(144)"},                        "Square root of 144"),
    ("calculate",    {"expression": "100000 * (1 + 0.12) ** 3"},         "Compound interest"),
    ("web_search",   {"query": "python programming language"},           "Web search: Python"),
    ("web_search",   {"query": "AI trends 2025"},                        "Web search: AI trends"),
    ("analyze_data", {"data": [10, 20, 30, 40, 50], "operation": "all"}, "Data analysis: all stats"),
    ("analyze_data", {"data": [100, 200, 300], "operation": "average"},  "Data analysis: average"),
    ("get_weather",  {"location": "Karachi"},                            "Weather: Karachi"),
    ("get_weather",  {"location": "London"},                             "Weather: London"),
]

passed = 0
for tool_name, args, description in tests:
    try:
        result = TOOL_FUNCTIONS[tool_name](**args)
        parsed = json.loads(result)
        status = parsed.get("status", "success")
        if status == "error":
            print(f"  ❌ FAIL  [{description}]: {parsed.get('error')}")
        else:
            print(f"  ✅ PASS  [{description}]")
            passed += 1
    except Exception as e:
        print(f"  ❌ ERROR [{description}]: {e}")

print(f"\n{'='*50}")
print(f"Results: {passed}/{len(tests)} tests passed")

"""---
## Generate Submission Files
"""

# ── requirements.txt ──────────────────────────────────────────
requirements = """groq>=0.9.0
python-dotenv>=1.0.0
"""

with open("requirements.txt", "w") as f:
    f.write(requirements)
print("✅ requirements.txt created")

# ── .env.example ───────────────────────────────────────────────
env_example = """# Copy this file to .env and fill in your keys
GROQ_API_KEY=your-groq-api-key-here
"""

with open(".env.example", "w") as f:
    f.write(env_example)
print("✅ .env.example created")

# ── examples.txt ───────────────────────────────────────────────
examples = """==============================================
MULTI-CAPABILITY AI ASSISTANT — Example Usage
==============================================

--- EXAMPLE 1: Email Writer (Formal) ---
Input:  "Write a formal email requesting a salary raise after 2 years of excellent performance"
Output: Subject: Request for Salary Review — [Your Name]

        Dear [Manager's Name],
        I am writing to formally request a review of my current compensation...
        [Full email body generated]

--- EXAMPLE 2: Email Writer (Friendly + Research) ---
Input:  "Write a friendly email about AI tools for productivity with research"
Output: [Uses web_search tool first, then writes email]
        Subject: Exciting AI Tools That Could Transform Our Workflow!
        ...

--- EXAMPLE 3: Smart Summarizer ---
Input:  "Summarize: [250-word article about climate change]"
Output: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        SUMMARY ANALYTICS
        Original: 250 words | 1500 chars | ~12 sentences
        Summary :  55 words |  320 chars
        Reduced : 78% shorter
        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        SUMMARY (MEDIUM)
        Climate change poses an existential threat...

--- EXAMPLE 4: Chat with Memory ---
You:        "My name is Ahmed, I'm learning Python."
Assistant:  "Nice to meet you, Ahmed! Python is a great choice..."
You:        "What was my name?"
Assistant:  "Your name is Ahmed, and you're learning Python!"

--- EXAMPLE 5: Calculator Tool ---
You:        "What is 15% of 8500?"
Assistant:  [Uses calculate tool: 8500 * 0.15]
            "15% of 8,500 is 1,275."

--- EXAMPLE 6: Data Analyzer ---
You:        "Analyze: 10, 25, 30, 45, 50"
Assistant:  Count: 5 | Sum: 160 | Avg: 32 | Max: 50 | Min: 10

--- EXAMPLE 7: Weather Tool ---
You:        "What's the weather in Karachi?"
Assistant:  "Karachi: 32°C, Partly Cloudy, Humidity: 72%, Wind: 18 km/h"
"""

with open("examples.txt", "w") as f:
    f.write(examples)
print("✅ examples.txt created")

# ── README.md ──────────────────────────────────────────────────
readme = """# 🤖 Multi-Capability AI Assistant
**Agentic AI Bootcamp — atomcamp | Session 2 Project**

A Python-based multi-capability AI assistant powered by **Groq API** (free), using the `llama-3.3-70b-versatile` model with tool/function calling.

---

## ✨ Capabilities

| # | Capability | Description |
|---|-----------|-------------|
| 1 | 📧 Enhanced Email Writer | Drafts emails in formal/friendly/casual tone; can research topics with web search |
| 2 | 📝 Smart Summarizer | Summarizes text with analytics (word count, reduction %) |
| 3 | 💬 Chat Assistant | Conversational chat with persistent memory across turns |

## 🔧 Tools

| # | Tool | Description |
|---|------|-------------|
| 1 | 🔢 Calculator | Evaluates math expressions safely (supports sqrt, log, trig) |
| 2 | 🔍 Web Search | Mock web search returning realistic results for common topics |
| 3 | 📊 Data Analyzer | Computes sum, average, max, min, median, std for number lists |
| 4 | 🌤️ Weather | Mock weather for Pakistani + global cities |

---

## 🚀 Installation

```bash
pip install -r requirements.txt
```

Copy `.env.example` to `.env` and add your Groq API key:
```
GROQ_API_KEY=your-key-here
```

## ▶️ Usage

### In Google Colab:
1. Add your Groq API key to Colab Secrets as `groq`
2. Run all cells in `Multi_Capability_AI_Assistant.ipynb`
3. Use the interactive chat cell or call methods directly

### As a Python script:
```python
from assistant import MultiCapabilityAssistant
import os

assistant = MultiCapabilityAssistant(api_key=os.environ["GROQ_API_KEY"])

# Email
print(assistant.write_email("Request time off", tone="formal"))

# Summarize
print(assistant.summarize("Long text here...", length="medium"))

# Chat
print(assistant.chat("What is the capital of Pakistan?"))

# Auto-route
print(assistant.process("Write a casual email to reschedule a meeting"))
```

---

## 📁 Files

```
Multi_Capability_AI_Assistant.ipynb  # Main notebook
requirements.txt                     # Dependencies
.env.example                         # API key template
examples.txt                         # Usage examples
README.md                            # This file
```

## 🔑 Getting a Free Groq API Key

1. Go to [console.groq.com](https://console.groq.com)
2. Sign up for a free account
3. Create an API key under "API Keys"
4. Add it to Colab Secrets as `groq`

---
*Built with ❤️ for atomcamp Agentic AI Bootcamp*
"""

with open("README.md", "w") as f:
    f.write(readme)
print("✅ README.md created")

print("\n🎉 All submission files generated!")
print("   requirements.txt | .env.example | examples.txt | README.md")